{{- range $nodepool := .Values.workerNodes.nodes }}
---
apiVersion: rke-machine-config.cattle.io/v1
kind: OpenstackConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
activeTimeout: "{{ $nodepool.activeTimeout | default $.Values.workerNodes.defaults.activeTimeout | default "200" }}"
applicationCredentialId: "{{ $.Values.infraConfig.applicationCredentialId | default "" }}"
applicationCredentialName: "{{ $.Values.infraConfig.applicationCredentialName | default "" }}"
applicationCredentialSecret: "{{ $.Values.infraConfig.applicationCredentialSecret | default "" }}"
authUrl: {{ $.Values.infraConfig.authUrl | quote }}
availabilityZone: {{ $.Values.infraConfig.availabilityZone | default "nova" }}
bootFromVolume: {{ $nodepool.bootFromVolume | default $.Values.workerNodes.defaults.bootFromVolume | default "false" }}
cacert: ""
configDrive: {{ $nodepool.configDrive | default $.Values.workerNodes.defaults.configDrive | default "false" }}
domainId: "{{ $.Values.infraConfig.domainId | default "" }}"
{{- if $.Values.infraConfig.domainName }}
domainName: {{ $.Values.infraConfig.domainName }}
{{- end }}
endpointType: {{ $.Values.infraConfig.endpointType | default "publicURL" }}
flavorId: "{{ $nodepool.flavorId | default $.Values.workerNodes.defaults.flavorId | default "" }}"
{{- if or ($nodepool.flavorName) ($.Values.workerNodes.defaults.flavorName) }}
flavorName: {{ ($nodepool.flavorName | default $.Values.workerNodes.defaults.flavorName) | quote }}
{{- end }}
floatingipPool: "{{ $nodepool.floatingipPool | default $.Values.workerNodes.defaults.floatingipPool | default "" }}"
imageId: "{{ $nodepool.imageId | default $.Values.workerNodes.defaults.imageId | default "" }}"
{{- if or ($nodepool.imageName) ($.Values.workerNodes.imageName) }}
imageName: {{ ($nodepool.imageName | default $.Values.workerNodes.imageName) | quote }}
{{- end }}
insecure: {{ $.Values.infraConfig.insecure | default "false" }}
ipVersion: "{{ $.Values.infraConfig.ipVersion | default "4" }}"
keypairName: {{ $.Values.infraConfig.keypairName }}
{{- if $.Values.infraConfig.netName }}
netName: {{ $.Values.infraConfig.netName }}
{{- end }}
novaNetwork: {{ $.Values.infraConfig.novaNetwork | default "false" }}
password: "{{ (lookup "v1" "Secret" $.Values.infraConfig.password.secret.namespace $.Values.infraConfig.password.secret.name).data.password | b64dec }}"
privateKeyFile: ""
region: {{ $.Values.infraConfig.region }}
sshPort: {{ $.Values.infraConfig.sshPort | default "22" | quote }}
sshUser: {{ $.Values.infraConfig.sshUser }}
secGroups: {{ ($nodepool.securityGroups | default $.Values.workerNodes.defaults.securityGroups) }}
tenantDomainId: "{{ $.Values.infraConfig.tenantDomainId | default "" }}"
tenantDomainName: "{{ $.Values.infraConfig.tenantDomainName | default "" }}"
tenantId: "{{ $.Values.infraConfig.tenantId | default "" }}"
tenantName: {{ $.Values.infraConfig.tenantName }}
userDataFile: ""
userDomainId: "{{ $.Values.infraConfig.userDomainId | default "" }}"
userDomainName: "{{ $.Values.infraConfig.userDomainName | default "" }}"
userId: "{{ $.Values.infraConfig.userId | default "" }}"
username: {{ $.Values.infraConfig.username }}
volumeDevicePath: ""
volumeId: ""
volumeName: ""
volumeSize: "{{ $nodepool.rootVolume.sizeGiB | default $.Values.workerNodes.defaults.rootVolume.sizeGiB | default "" }}"
volumeType: "{{ $nodepool.rootVolume.volumeType | default $.Values.workerNodes.defaults.rootVolume.volumeType | default "" }}"
{{- end }}