{{- if .Values.storage.cephRBD.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-ceph-rbd
  namespace: fleet-default
spec:
  chart: "ceph-csi-rbd"
  repoName: {{ .Values.cluster.addonsRepoName }}
  releaseName: "ceph-csi-rbd"
  version: 3.10.1
  {{- if not (empty .Values.storage.cephRBD.customValues) }}
  values:
    {{ toYaml .Values.storage.cephRBD.customValues }}
  {{- else }}
  values:
    csiConfig:
      - clusterID: {{ .Values.storage.cephRBD.clusterID }}
        monitors:
          {{- range .Values.storage.cephRBD.monitorList }}
          - {{ . }}
          {{- end }}
        readAffinity:
          enabled: true
          crushLocationLabels:
            - topology.kubernetes.io/region
            - topology.kubernetes.io/zone
    storageClass:
      create: true
      name: default-ceph-rbd-sg
      clusterID: {{ .Values.storage.cephRBD.clusterID }}
      pool: {{ .Values.storage.cephRBD.pool }}
      reclaimPolicy: {{ .Values.storage.cephRBD.reclaimPolicy }}
      encrypted: false
    secret:
      create: true
      userID: {{ .Values.storage.cephRBD.userID }}
      userKey: {{ .Values.storage.cephRBD.userKey }}
    readAffinity:
      enabled: true
    provisioner:
      replicaCount: {{ .Values.storage.cephRBD.provisionerReplicaCount }}
      enableHostNetwork: {{ .Values.storage.cephRBD.enabledHostNetwork }}
    logLevel: 5
    sidecarLogLevel: 1
  {{- end }}
  defaultNamespace: "ceph-system"
  targets:
    - clusterName: {{ .Values.cluster.name }}
{{- end }}